# Postgres configuration
default: &default
  adapter: postgresql
  host: localhost # necessary for Postgres peer security
  encoding: unicode
  username: postgres
  pool: 5

development: &development
  <<: *default
  database: pop_development

test:
  <<: *development
  database: pop_test
