# Postgres configuration
default: &default
  adapter: postgresql
  host: localhost # necessary for Postgres peer security
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: pop_development
  username: XXXX
  password: XXXX

test:
  <<: *development
  database: pop_test
